
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS salary;
DROP TABLE IF EXISTS visitor;


CREATE TABLE user(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT UNIQUE NOT NULL,
   name TEXT NOT NULL,
   password TEXT NOT NULL
);


CREATE TABLE income (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Block TEXT NOT NULL,
    UnitNo INTEGER NOT NULL,
    MaintenanceFee INTEGER NOT NULL,
    Due INTEGER NOT NULL
);

CREATE TABLE Payment(

	id INTEGER PRIMARY KEY AUTOINCREMENT,
	income_id INTEGER NOT NULL,
	amount INTEGER NOT NULL,
	Pdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (income_id) REFERENCES income(id)
   
);

CREATE TABLE expenses(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Vname TEXT NOT NULL,
    cause TEXT NOT NULL,
    phone INTEGER NOT NULL,
    fee INTEGER NOT NULL,
    ispaid INTEGER NOT NULL DEFAULT 0,
    lastsalary TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE salary(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    expense_id INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    Pdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (expense_id) REFERENCES expenses(id)
);

CREATE TABLE visitor(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    visname TEXT NOT NULL,
    category TEXT NOT NULL,
    phoneno INTEGER NOT NULL,
    unitno TEXT NOT NULL,
    datein TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)

